package main

import (
	"crypto/sha256"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
	"time"

	"golang.org/x/time/rate"
)

// The argon2 fixtures below were generated by the SAME library code-server
// verifies passwords with — the `argon2` npm package — for the password
// "correct horse battery staple", and that library's own argon2.verify accepts
// them. They are checked in verbatim so the parser is pinned against real
// code-server output, not an assumption about the PHC format. Regenerate with:
//
//	node -e 'a=require("argon2");a.hash("correct horse battery staple",
//	  {type:a.argon2id}).then(console.log)'
const (
	fixturePassword = "correct horse battery staple"
	// argon2id, the argon2 npm defaults (m=65536,t=3,p=4) — what `npx argon2-cli -e` emits.
	fixtureArgon2id = "$argon2id$v=19$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo"
	// argon2i, the other OWASP-listed variant a user might paste.
	fixtureArgon2i = "$argon2i$v=19$m=65536,t=3,p=4$01lU9wzCBbH+XYO8CWRWtQ$Z1nYejk5bhLHJrEQGWjWYCcZ7rXetMb7AY0huBrBuUI"
	// argon2id with the OWASP low-memory params, to prove m/t/p are read from the
	// string and not hardcoded.
	fixtureArgon2idLowMem = "$argon2id$v=19$m=19456,t=2,p=1$QY8RGHexB8LW3CNaBQn9DA$6ZUOeVHpiLrKPcLcsPFQchakuGRpiN4T8z3mgTfYK7U"
	// sha256(fixturePassword) hex — code-server's legacy HASHED_PASSWORD form.
	fixtureSHA256 = "c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a"
)

// TestVerifyArgon2Real proves the argon2 path verifies real code-server hashes
// (all supported variants and parameter sets) and rejects the wrong password.
func TestVerifyArgon2Real(t *testing.T) {
	for _, phc := range []string{fixtureArgon2id, fixtureArgon2i, fixtureArgon2idLowMem} {
		c := &credential{method: methodArgon2, hash: phc}
		if !c.verify(fixturePassword) {
			t.Errorf("argon2 verify rejected the correct password for %s", phc)
		}
		if c.verify("wrong password") {
			t.Errorf("argon2 verify accepted a wrong password for %s", phc)
		}
		if c.verify("") {
			t.Errorf("argon2 verify accepted an empty password for %s", phc)
		}
	}
}

// TestParseArgon2 pins the PHC parser: real strings decode to the exact params,
// and every malformed or unsupported shape fails closed.
func TestParseArgon2(t *testing.T) {
	got, err := parseArgon2(fixtureArgon2id)
	if err != nil {
		t.Fatalf("parseArgon2(real argon2id) errored: %v", err)
	}
	if got.variant != "argon2id" || got.m != 65536 || got.t != 3 || got.p != 4 {
		t.Fatalf("parsed params = %+v, want argon2id m=65536 t=3 p=4", got)
	}
	if len(got.salt) != 16 || len(got.hash) != 32 {
		t.Fatalf("salt/hash lengths = %d/%d, want 16/32", len(got.salt), len(got.hash))
	}

	bad := []struct{ name, phc string }{
		{"empty", ""},
		{"too few fields", "$argon2id$v=19$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA"},
		{"too many fields", fixtureArgon2id + "$extra"},
		{"missing leading empty", "argon2id$v=19$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo"},
		{"argon2d unsupported", "$argon2d$v=19$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo"},
		{"wrong version", "$argon2id$v=18$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo"},
		{"bad params", "$argon2id$v=19$m=lots,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo"},
		{"bad salt b64", "$argon2id$v=19$m=65536,t=3,p=4$not!base64$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo"},
		{"empty hash", "$argon2id$v=19$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$"},
	}
	for _, b := range bad {
		t.Run(b.name, func(t *testing.T) {
			if _, err := parseArgon2(b.phc); err == nil {
				t.Fatalf("parseArgon2(%q) succeeded, want error", b.phc)
			}
		})
	}
}

// TestVerifySHA256AndPlain covers the legacy hex and plaintext credentials.
func TestVerifySHA256AndPlain(t *testing.T) {
	sha := &credential{method: methodSHA256, hash: fixtureSHA256}
	if !sha.verify(fixturePassword) {
		t.Error("sha256 verify rejected the correct password")
	}
	if sha.verify("wrong") {
		t.Error("sha256 verify accepted a wrong password")
	}

	plain := &credential{method: methodPlain, plain: "swordfish"}
	if !plain.verify("swordfish") {
		t.Error("plain verify rejected the correct password")
	}
	if plain.verify("Swordfish") || plain.verify("") {
		t.Error("plain verify accepted a wrong password")
	}
}

func TestIsSHA256Hex(t *testing.T) {
	if !isSHA256Hex(fixtureSHA256) {
		t.Error("real sha256 hex rejected")
	}
	for _, s := range []string{"", "abc", strings.Repeat("g", 64), fixtureSHA256 + "0"} {
		if isSHA256Hex(s) {
			t.Errorf("isSHA256Hex(%q) = true, want false", s)
		}
	}
}

// TestNewCredential pins the env-driven method selection and the fail-closed
// rejection of a malformed HASHED_PASSWORD (we never silently fall back to a
// weaker check or to no password at all).
func TestNewCredential(t *testing.T) {
	cases := []struct {
		name       string
		hashed     string
		password   string
		wantMethod int
		wantErr    bool
	}{
		{"argon2id", fixtureArgon2id, "", methodArgon2, false},
		{"argon2i", fixtureArgon2i, "", methodArgon2, false},
		{"sha256 hex", fixtureSHA256, "", methodSHA256, false},
		{"sha256 uppercase normalized", strings.ToUpper(fixtureSHA256), "", methodSHA256, false},
		{"hashed wins over password", fixtureSHA256, "ignored", methodSHA256, false},
		{"plain", "", "hunter2", methodPlain, false},
		{"argon2 marker but malformed", "$argon2id$v=19$nope", "", 0, true},
		{"argon2d unsupported", "$argon2d$v=19$m=65536,t=3,p=4$AbLdZvp4ko8nfo/P4owEIA$q2sRD59XiQCpUvXDF/RS2/LFRv1KaDJLoV61XK21Qlo", "", 0, true},
		{"hashed not hash nor argon", "definitely-not-a-hash", "", 0, true},
		{"nothing set", "", "", 0, true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			t.Setenv("HASHED_PASSWORD", c.hashed)
			t.Setenv("PASSWORD", c.password)
			cred, err := newCredential()
			if c.wantErr {
				if err == nil {
					t.Fatalf("newCredential() = %+v, want error", cred)
				}
				return
			}
			if err != nil {
				t.Fatalf("newCredential() errored: %v", err)
			}
			if cred.method != c.wantMethod {
				t.Fatalf("method = %d, want %d", cred.method, c.wantMethod)
			}
			if c.wantMethod == methodSHA256 && cred.hash != fixtureSHA256 {
				t.Fatalf("sha256 hash not normalized to lowercase: %q", cred.hash)
			}
		})
	}
}

// TestToken locks the HMAC token: round-trip, expiry, tamper-resistance, the
// secret binding, and the domain separation that stops a session cookie from
// being replayed as a WebSocket bearer.
func TestToken(t *testing.T) {
	secret := deriveSecret(&credential{method: methodPlain, plain: "swordfish"})
	other := deriveSecret(&credential{method: methodPlain, plain: "different"})
	now := time.Unix(1_700_000_000, 0)

	tok := mintToken(secret, ctxWS, now, wsTokenTTL)
	if !verifyToken(secret, ctxWS, tok, now) {
		t.Fatal("fresh token failed to verify")
	}
	if !verifyToken(secret, ctxWS, tok, now.Add(wsTokenTTL)) {
		t.Fatal("token rejected exactly at expiry (should be inclusive)")
	}
	if verifyToken(secret, ctxWS, tok, now.Add(wsTokenTTL+time.Second)) {
		t.Fatal("expired token verified")
	}
	if verifyToken(other, ctxWS, tok, now) {
		t.Fatal("token verified under a different secret (password rotation must invalidate)")
	}
	if verifyToken(secret, ctxSession, tok, now) {
		t.Fatal("ws token verified in the session context (domain separation broken)")
	}

	// A session cookie must not be presentable as a ws bearer, and vice versa.
	session := mintToken(secret, ctxSession, now, sessionTTL)
	if verifyToken(secret, ctxWS, session, now) {
		t.Fatal("session token accepted as a ws token")
	}

	for _, bad := range []string{"", "noseparator", "notanumber.YWJj", tok + "x", "." + tok} {
		if verifyToken(secret, ctxWS, bad, now) {
			t.Errorf("verifyToken accepted malformed token %q", bad)
		}
	}
}

// TestDeriveSecret: deterministic for a given password, divergent across
// passwords, and full-length.
func TestDeriveSecret(t *testing.T) {
	a := deriveSecret(&credential{method: methodPlain, plain: "swordfish"})
	b := deriveSecret(&credential{method: methodPlain, plain: "swordfish"})
	c := deriveSecret(&credential{method: methodPlain, plain: "swordfish2"})
	if len(a) != 32 {
		t.Fatalf("secret length = %d, want 32", len(a))
	}
	if string(a) != string(b) {
		t.Fatal("deriveSecret is not deterministic for the same password")
	}
	if string(a) == string(c) {
		t.Fatal("deriveSecret collided across different passwords")
	}
}

// newTestSelfHost builds a selfHost with a known plaintext credential and a full
// rate-limit bucket, for the HTTP-surface tests.
func newTestSelfHost(t *testing.T) *selfHost {
	t.Helper()
	cred := &credential{method: methodPlain, plain: fixturePassword}
	return &selfHost{
		cred:    cred,
		secret:  deriveSecret(cred),
		origins: nil,
		limiter: rate.NewLimiter(rate.Limit(float64(loginPerMin)/60.0), loginBurst),
	}
}

func postLogin(sh *selfHost, password string) *httptest.ResponseRecorder {
	body := url.Values{"password": {password}}.Encode()
	r := httptest.NewRequest(http.MethodPost, "/__console/login", strings.NewReader(body))
	r.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	w := httptest.NewRecorder()
	sh.handleLogin(w, r)
	return w
}

// getToken performs GET /__console/token with the given session cookie (nil
// for none) and Sec-Fetch-Site header ("" for absent).
func getToken(sh *selfHost, cookie *http.Cookie, fetchSite string) *httptest.ResponseRecorder {
	r := httptest.NewRequest(http.MethodGet, "/__console/token", nil)
	if cookie != nil {
		r.AddCookie(cookie)
	}
	if fetchSite != "" {
		r.Header.Set("Sec-Fetch-Site", fetchSite)
	}
	w := httptest.NewRecorder()
	sh.handleToken(w, r)
	return w
}

// TestLoginTokenFlow walks the real browser handshake: bad password is refused,
// a good password mints a hardened session cookie, that cookie exchanges for a
// ws token, and the token authorizes the socket — while a missing/forged cookie
// and a cross-site fetch are refused.
func TestLoginTokenFlow(t *testing.T) {
	sh := newTestSelfHost(t)

	if w := postLogin(sh, "wrong"); w.Code != http.StatusUnauthorized {
		t.Fatalf("bad-password login = %d, want 401", w.Code)
	}

	w := postLogin(sh, fixturePassword)
	if w.Code != http.StatusNoContent {
		t.Fatalf("good-password login = %d, want 204", w.Code)
	}
	var session *http.Cookie
	for _, ck := range w.Result().Cookies() {
		if ck.Name == sessionCookie {
			session = ck
		}
	}
	if session == nil {
		t.Fatal("login did not set the session cookie")
	}
	// No Secure attribute by design: the documented flow is plain HTTP on a LAN
	// host, where browsers drop Secure cookies — re-adding it silently breaks
	// every non-TLS self-host login (see handleLogin). Pin its absence.
	if session.Secure {
		t.Fatal("session cookie sets Secure: breaks the documented plain-HTTP login flow (see handleLogin)")
	}
	if !session.HttpOnly || session.SameSite != http.SameSiteStrictMode || session.Path != "/__console" {
		t.Fatalf("session cookie not hardened: %+v", session)
	}

	// No cookie -> 401.
	if w := getToken(sh, nil, ""); w.Code != http.StatusUnauthorized {
		t.Fatalf("token without cookie = %d, want 401", w.Code)
	}

	// Forged cookie -> 401.
	if w := getToken(sh, &http.Cookie{Name: sessionCookie, Value: "9999999999.forgedmac"}, ""); w.Code != http.StatusUnauthorized {
		t.Fatalf("token with forged cookie = %d, want 401", w.Code)
	}

	// Cross-site fetch with a valid cookie -> 403 (defense in depth atop SameSite).
	if w := getToken(sh, session, "cross-site"); w.Code != http.StatusForbidden {
		t.Fatalf("cross-site token fetch = %d, want 403", w.Code)
	}

	// Valid same-origin fetch -> 200 + a ws token that authorizes the socket.
	tw := getToken(sh, session, "same-origin")
	if tw.Code != http.StatusOK {
		t.Fatalf("valid token fetch = %d, want 200", tw.Code)
	}
	wsToken := strings.TrimSpace(tw.Body.String())
	if !verifyToken(sh.secret, ctxWS, wsToken, time.Now()) {
		t.Fatal("minted ws token does not verify in the ws context")
	}

	// The ws token presented on the subprotocol authorizes; garbage and a
	// replayed session cookie value do not.
	auth := sh.wsAuth()
	if err := auth.authorize(wsRequest(subprotocol + ", " + wsToken)); err != nil {
		t.Fatalf("valid ws token rejected by wsAuth: %v", err)
	}
	if err := auth.authorize(wsRequest(subprotocol + ", garbage")); err == nil {
		t.Fatal("wsAuth accepted a garbage token")
	}
	if err := auth.authorize(wsRequest(subprotocol + ", " + session.Value)); err == nil {
		t.Fatal("wsAuth accepted the session cookie value as a ws token")
	}
	if err := auth.authorize(wsRequest(subprotocol)); err == nil {
		t.Fatal("wsAuth accepted a request with no token")
	}
}

func wsRequest(proto string) *http.Request {
	r := httptest.NewRequest(http.MethodGet, "/__console", nil)
	r.Header.Set("Sec-WebSocket-Protocol", proto)
	return r
}

// TestLoginRateLimit proves the brute-force gate trips: once the burst is spent,
// further attempts are 429 regardless of password correctness, so the limiter
// runs before (and independently of) verification.
func TestLoginRateLimit(t *testing.T) {
	sh := newTestSelfHost(t)
	for i := 0; i < loginBurst; i++ {
		if w := postLogin(sh, "wrong"); w.Code == http.StatusTooManyRequests {
			t.Fatalf("attempt %d throttled before the burst was spent", i+1)
		}
	}
	if w := postLogin(sh, "wrong"); w.Code != http.StatusTooManyRequests {
		t.Fatalf("attempt past the burst = %d, want 429", w.Code)
	}
	if w := postLogin(sh, fixturePassword); w.Code != http.StatusTooManyRequests {
		t.Fatalf("correct password past the burst = %d, want 429", w.Code)
	}
}

// TestUIAndAssets confirms the embedded UI and vendored xterm assets ship and
// serve, and that a missing asset is a clean 404 (not a panic or a directory
// listing escape).
func TestUIAndAssets(t *testing.T) {
	sh := newTestSelfHost(t)
	uw := httptest.NewRecorder()
	sh.handleUI(uw, httptest.NewRequest(http.MethodGet, "/__console/ui", nil))
	if uw.Code != http.StatusOK || !strings.Contains(uw.Body.String(), "EnvHaven Terminal") {
		t.Fatalf("handleUI = %d, body missing the page", uw.Code)
	}
	if ct := uw.Header().Get("Content-Type"); !strings.HasPrefix(ct, "text/html") {
		t.Fatalf("handleUI content-type = %q, want text/html", ct)
	}

	h := assetsHandler()
	for _, name := range []string{"xterm.js", "xterm.css", "addon-fit.js"} {
		w := httptest.NewRecorder()
		h.ServeHTTP(w, httptest.NewRequest(http.MethodGet, "/__console/assets/"+name, nil))
		if w.Code != http.StatusOK || w.Body.Len() == 0 {
			t.Fatalf("asset %s = %d, len %d", name, w.Code, w.Body.Len())
		}
	}
	w := httptest.NewRecorder()
	h.ServeHTTP(w, httptest.NewRequest(http.MethodGet, "/__console/assets/nope.js", nil))
	if w.Code != http.StatusNotFound {
		t.Fatalf("missing asset = %d, want 404", w.Code)
	}
}

// TestVendoredAssetsPristine pins the vendored xterm build byte-for-byte to
// the upstream npm artifacts recorded in ui/assets/LICENSE (@xterm/xterm@6.0.0,
// @xterm/addon-fit@0.11.0). terminal.html reaches into xterm internals for the
// predictive-echo overlay, so a drifted or locally-edited bundle must fail
// loudly here, never ship silently. When deliberately updating xterm: replace
// the files, then update these hashes and the versions in ui/assets/LICENSE.
func TestVendoredAssetsPristine(t *testing.T) {
	want := map[string]string{
		"ui/assets/xterm.js":     "14903579ff54664cd72f8e8699e6961a6272c21863ec1c3b118cdc8af5d4a972",
		"ui/assets/xterm.css":    "854a7c0fb70e8b1a083c16797ab827299fb18744f5ad34f227b48337e33293c6",
		"ui/assets/addon-fit.js": "ba3ea256ce0620a0992a197d6c9baea64823fc93d8da07a9e366ca9943c18527",
	}
	for name, hash := range want {
		b, err := assetsFS.ReadFile(name)
		if err != nil {
			t.Fatalf("read embedded %s: %v", name, err)
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(b)); got != hash {
			t.Errorf("%s drifted from the recorded upstream build:\n  got  sha256 %s\n  want sha256 %s\nsee ui/assets/LICENSE for the update procedure", name, got, hash)
		}
	}
}

// TestLoginBodyCap proves the MaxBytesReader cap rejects an oversized login body
// (instead of buffering it unbounded) and returns the clean 400 path.
func TestLoginBodyCap(t *testing.T) {
	sh := newTestSelfHost(t)
	body := "password=" + strings.Repeat("a", 5000) // > the 4096 cap
	r := httptest.NewRequest(http.MethodPost, "/__console/login", strings.NewReader(body))
	r.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	w := httptest.NewRecorder()
	sh.handleLogin(w, r)
	if w.Code != http.StatusBadRequest {
		t.Fatalf("oversized login body = %d, want 400", w.Code)
	}
}

// TestRootRedirect proves the bare host root sends the operator to the terminal
// page so the documented http://host:7681/ URL resolves.
func TestRootRedirect(t *testing.T) {
	sh := newTestSelfHost(t)
	w := httptest.NewRecorder()
	sh.handleRoot(w, httptest.NewRequest(http.MethodGet, "/", nil))
	if w.Code != http.StatusFound {
		t.Fatalf("root status = %d, want 302", w.Code)
	}
	if loc := w.Header().Get("Location"); loc != "/__console/ui" {
		t.Fatalf("root redirect Location = %q, want /__console/ui", loc)
	}
}
